### ISSUE TITLE
New name: Non-binary Environmental Archive Format

### ISSUE THREAD

**Issue by iosifescu** [GEUS-PROMICE/NEAD#10]
Based on feedback received, I would suggest to change the N in NEAD from "New" to "Non-binary". Consequently, the NEAD initials will mean "Non-binary Environmental Archive Data" format.

**Comment by mankoff** [comment]
Is the F correct? In which case NEAF? Or is it "Non-binary Environmental Archive Data"?

**Comment by iosifescu** [comment]
Indeed, it is "Non-binary Environmental Archive Data" format, thanks for spotting it!
