### ISSUE TITLE
New separated global metadata header and fields sections

### ISSUE THREAD

**Issue by iosifescu** [GEUS-PROMICE/NEAD#2]
Dear Ken,

Thanks for changing the column_delimiter -> field_delimiter.

As discussed, it might be better to change:
 
headerstart      ::= '#' ' ' '[HEADER]' newline
to
headerstart      ::= '#' ' ' '[METADATA]' newline

and to add all the fields related keys in a '#' ' ' '[FIELDS]' newline section.

Best, Ionut

**Comment by mankoff** [comment]
Yes, but I was waiting for @bavay to comment on this suggested change before implementing it.

**Comment by iosifescu** [comment]
ok

**Comment by bavay** [comment]
Sorry, I should have commented earlier... Yes, I think Ionut's idea is a very good one!
