### ISSUE TITLE
data_citation key in the [METADATA] section

### ISSUE THREAD

**Issue by iosifescu** [GEUS-PROMICE/NEAD#8]
Let's add a RECOMMENDED data_citation key in the [METADATA] section. The value of this key is text, preferably quoted, e.g. "Haeni, Matthias; Gessler, Arthur; Rebetez, Martine (2019). Jussy, Switzerland: Long-term forest meteorological data from the Long-term Forest Ecosystem Research Programme (LWF), from 1997 onwards. EnviDat. doi:10.16904/envidat.100"

We will change our new GC-Net exports accordingly, and you'll receive the new NEAD exports for Baptiste as examples. I will also discuss with Derek, to define a proper citation for Koni's data.

**Comment by iosifescu** [comment]
In addition, by using a data_citation key, we do not need to bloat the NEAD specifications with too much metadata about authors and ensures that the data is cited correctly.

**Comment by mankoff** [comment]
I suggest "reference" rather than "data_citation".

**Comment by iosifescu** [comment]
Agree - "reference" is more user friendly.
