### ISSUE TITLE
add_offset and scale_factor are for packed data, not MKS conversion

### ISSUE THREAD

**Issue by mankoff** [GEUS-PROMICE/NEAD#9]
https://www.unidata.ucar.edu/software/netcdf/workshops/2010/bestpractices/Packing.html

These fields should be maintained as optional to reduce data file size, but their purpose is not MKS conversion. 

We need two new fields for MKS, perhaps `MKS_offset` and `MKS_factor`?

**Comment by mankoff** [comment]
Or the previous implementation: `units_offset` and `units_multiplier`

**Comment by bavay** [comment]
I think MKS_xxx is not that great of a choice since we should be based on SI and not "only" MKS... I find units_xxx clearer, but if somebody has good reasons to prefer SI_xxx I'm willing to hear!
